// ═══════════════════════════════════════════════════════════════════
// BLUESHELL - Rich Platform Page Content
// Provides detailed, interactive content for every platform page
// ═══════════════════════════════════════════════════════════════════

function pgCode(code, lang) {
    return `<div style="background:#0d0d0d;border:1px solid #333;border-radius:4px;margin:10px 0;overflow:hidden"><div style="display:flex;justify-content:space-between;padding:5px 10px;background:#1a1a1a;border-bottom:1px solid #333"><span style="color:#666;font-size:0.75em">${lang||'code'}</span><button onclick="navigator.clipboard.writeText(this.closest('div').parentElement.querySelector('code').innerText).then(()=>{this.textContent='COPIED!';setTimeout(()=>this.textContent='Copy',1500)})" style="background:none;border:1px solid #444;color:#0f0;padding:2px 10px;cursor:pointer;font-family:monospace;font-size:0.75em">Copy</button></div><pre style="margin:0;padding:12px;overflow-x:auto"><code style="color:#0f0;font-size:0.82em;line-height:1.5">${code.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</code></pre></div>`;
}

function pgBack() {
    return `<button class="btn-hack" onclick="goHome()" style="margin-bottom:15px">◂ BACK TO DASHBOARD</button>`;
}

// ═══════════════════════════════════════════════════════════════════
// RICH PAGE CONTENT - Detailed content for every platform
// ═══════════════════════════════════════════════════════════════════

const richPageContent = {};

// ─── SPLUNK ──────────────────────────────────────────────────────
richPageContent.splunk = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">SPLUNK ENTERPRISE SECURITY</h1>
    <span class="card-tag" style="position:static">SIEM</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">The most widely deployed SIEM platform for security operations, threat detection, and incident investigation.</p>

<div class="pg-section">
    <div class="pg-section-title">OVERVIEW</div>
    <p style="color:var(--text-secondary);line-height:1.7;font-size:0.88em">
        Splunk Enterprise Security (ES) is a premium SIEM solution built on the Splunk data platform. It ingests machine data from virtually any source — firewalls, endpoints, cloud services, applications — and enables real-time detection, investigation, and response. Splunk's power comes from SPL (Search Processing Language), a flexible query language that lets analysts search, correlate, and visualize security events at scale.
    </p>
    <p style="color:var(--text-secondary);line-height:1.7;font-size:0.88em;margin-top:10px">
        For SOC teams, Splunk ES provides Notable Events (alerts mapped to kill chain stages), Risk-Based Alerting (RBA) to reduce alert fatigue, Adaptive Response for automated actions, and pre-built dashboards for security posture monitoring.
    </p>
</div>

<div class="pg-section">
    <div class="pg-section-title">ARCHITECTURE</div>
    <div class="pg-ascii-art"><pre>
    ┌──────────────┐     ┌──────────────┐     ┌──────────────┐
    │  Data Sources │     │  Forwarders  │     │   Indexers   │
    │  ─────────── │────▶│  ─────────── │────▶│  ─────────── │
    │  Firewall    │     │  Universal   │     │  Store &     │
    │  Endpoints   │     │  Heavy       │     │  Index Data  │
    │  Cloud Logs  │     │  HTTP Event  │     │              │
    │  Syslog      │     │  Collector   │     └──────┬───────┘
    └──────────────┘     └──────────────┘            │
                                                     ▼
    ┌──────────────┐     ┌──────────────┐     ┌──────────────┐
    │  Dashboards  │     │ Search Heads │     │  Enterprise  │
    │  ─────────── │◀────│  ─────────── │◀────│  Security    │
    │  SOC Views   │     │  SPL Queries │     │  ─────────── │
    │  Reports     │     │  Saved Search│     │  Notable     │
    │  Alerts      │     │  Lookups     │     │  Events, RBA │
    └──────────────┘     └──────────────┘     └──────────────┘
    </pre></div>
</div>

<div class="pg-section">
    <div class="pg-section-title">KEY CONCEPTS</div>
    <table class="pg-table">
        <tr><th>Concept</th><th>Description</th></tr>
        <tr><td>Index</td><td>Data repository where events are stored. Common: main, wineventlog, syslog, firewall</td></tr>
        <tr><td>Sourcetype</td><td>Data format identifier. Tells Splunk how to parse events (e.g., WinEventLog:Security)</td></tr>
        <tr><td>SPL</td><td>Search Processing Language — Splunk's query language for searching, filtering, and transforming data</td></tr>
        <tr><td>Notable Event</td><td>Security alert generated by a correlation search in Enterprise Security</td></tr>
        <tr><td>Risk-Based Alerting</td><td>Assigns risk scores to entities instead of firing individual alerts — reduces alert fatigue by 90%+</td></tr>
        <tr><td>Correlation Search</td><td>Scheduled SPL query that creates Notable Events when conditions are met</td></tr>
        <tr><td>Lookup</td><td>Reference table for enrichment (CSV, KV store, or external)</td></tr>
        <tr><td>Macro</td><td>Reusable SPL snippet referenced by name in searches</td></tr>
        <tr><td>Data Model</td><td>Structured schema for CIM-compliant data acceleration</td></tr>
        <tr><td>CIM</td><td>Common Information Model — normalizes field names across data sources</td></tr>
    </table>
</div>

<div class="pg-section">
    <div class="pg-section-title">SPL QUERY ESSENTIALS</div>

    <h4 style="color:#0f0;margin-top:15px">1. Basic Search</h4>
    ${pgCode(`index=wineventlog sourcetype="WinEventLog:Security" EventCode=4625
| stats count by src_ip, user
| where count > 5
| sort -count`, 'spl')}

    <h4 style="color:#0f0;margin-top:15px">2. Process Execution Monitoring</h4>
    ${pgCode(`index=sysmon EventCode=1
| search (process_name="powershell.exe" OR process_name="cmd.exe")
| eval suspicious=if(match(CommandLine, "(?i)(encodedcommand|bypass|hidden|downloadstring|iex|invoke-expression)"), "YES", "NO")
| where suspicious="YES"
| table _time, ComputerName, user, process_name, CommandLine, ParentCommandLine
| sort -_time`, 'spl')}

    <h4 style="color:#0f0;margin-top:15px">3. Brute Force Detection</h4>
    ${pgCode(`index=wineventlog EventCode=4625
| bin _time span=10m
| stats count as fail_count dc(TargetUserName) as unique_users values(TargetUserName) as users by src_ip, _time
| where fail_count > 20 OR unique_users > 5
| sort -fail_count`, 'spl')}

    <h4 style="color:#0f0;margin-top:15px">4. Lateral Movement — Pass-the-Hash</h4>
    ${pgCode(`index=wineventlog EventCode=4624 Logon_Type=3 AuthenticationPackageName=NTLM
| stats count dc(ComputerName) as unique_hosts values(ComputerName) as hosts by TargetUserName, IpAddress
| where unique_hosts > 3
| sort -unique_hosts`, 'spl')}

    <h4 style="color:#0f0;margin-top:15px">5. DNS Exfiltration Detection</h4>
    ${pgCode(`index=dns
| eval query_length=len(query)
| where query_length > 50
| stats count avg(query_length) as avg_len max(query_length) as max_len dc(query) as unique_queries by src_ip
| where unique_queries > 100 AND avg_len > 40
| sort -unique_queries`, 'spl')}

    <h4 style="color:#0f0;margin-top:15px">6. Risk-Based Alerting (RBA) Pattern</h4>
    ${pgCode(`| from datamodel:"Risk"."All_Risk"
| stats sum(calculated_risk_score) as total_risk values(search_name) as detections dc(search_name) as detection_count by risk_object
| where total_risk > 100
| sort -total_risk`, 'spl')}

    <h4 style="color:#0f0;margin-top:15px">7. Correlation Search Template</h4>
    ${pgCode(`index=wineventlog (EventCode=4720 OR EventCode=4732 OR EventCode=4728)
| eval action=case(
    EventCode=4720, "Account Created",
    EventCode=4732, "Added to Local Group",
    EventCode=4728, "Added to Global Group")
| stats count values(action) as actions values(TargetUserName) as target_users by SubjectUserName, ComputerName
| where count >= 2
| eval risk_score=count*25`, 'spl')}
</div>

<div class="pg-section">
    <div class="pg-section-title">DETECTION RULE CREATION STEPS</div>
    <div class="pg-step"><div class="pg-step-num">1</div><div class="pg-step-text"><strong>Define the use case:</strong> What behavior are you detecting? Map to MITRE ATT&CK technique. Example: T1059.001 PowerShell execution with encoded commands.</div></div>
    <div class="pg-step"><div class="pg-step-num">2</div><div class="pg-step-text"><strong>Identify data sources:</strong> What index/sourcetype contains the relevant events? Ensure data is being ingested and parsed correctly.</div></div>
    <div class="pg-step"><div class="pg-step-num">3</div><div class="pg-step-text"><strong>Write the SPL query:</strong> Start with a basic search, refine with stats/eval/where commands. Test against historical data.</div></div>
    <div class="pg-step"><div class="pg-step-num">4</div><div class="pg-step-text"><strong>Tune for false positives:</strong> Run for 7 days in audit mode. Add exclusions for known-good behavior (admin scripts, SCCM, etc.).</div></div>
    <div class="pg-step"><div class="pg-step-num">5</div><div class="pg-step-text"><strong>Create as Correlation Search:</strong> Settings > Searches, Reports > New Correlation Search. Set schedule (every 5-15 min).</div></div>
    <div class="pg-step"><div class="pg-step-num">6</div><div class="pg-step-text"><strong>Configure response:</strong> Set severity, create Notable Event, optionally trigger Adaptive Response (email, script, containment).</div></div>
    <div class="pg-step"><div class="pg-step-num">7</div><div class="pg-step-text"><strong>Document and review:</strong> Document the rule in your detection catalog. Review weekly for FP rate and effectiveness.</div></div>
</div>

<div class="pg-section">
    <div class="pg-section-title">BEST PRACTICES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Use CIM-Compliant Data</h4><p>Map all data to Common Information Model fields. This ensures your searches work across all data sources and makes ES correlation searches function correctly.</p></div>
        <div class="pg-info-card"><h4>Implement RBA</h4><p>Risk-Based Alerting reduces alert fatigue by 90%. Assign risk scores to users/hosts instead of creating individual alerts. Alert only when cumulative risk exceeds threshold.</p></div>
        <div class="pg-info-card"><h4>Use Accelerated Data Models</h4><p>For dashboards and frequent searches, use tstats against accelerated data models instead of raw SPL searches. 10-100x faster.</p></div>
        <div class="pg-info-card"><h4>Index-Time vs Search-Time</h4><p>Do heavy field extractions at index time for high-volume data. Use search-time extractions for ad-hoc analysis. Balance performance vs flexibility.</p></div>
        <div class="pg-info-card"><h4>Lookup Enrichment</h4><p>Create lookups for asset inventory, identity info, threat intel, and known-good lists. Automatic lookups apply enrichment at search time.</p></div>
        <div class="pg-info-card"><h4>Saved Search Optimization</h4><p>Use earliest/latest time modifiers. Avoid wildcard-only searches. Pre-filter with indexed fields before applying search-time fields.</p></div>
    </div>
</div>

<div class="pg-section">
    <div class="pg-section-title">TRAINING ROADMAP</div>
    <table class="pg-table">
        <tr><th>Level</th><th>Topics</th><th>Duration</th></tr>
        <tr><td><span class="pg-badge pg-badge-green">Beginner</span></td><td>SPL basics (search, fields, stats, table), navigation, time picker, basic reports</td><td>1-2 weeks</td></tr>
        <tr><td><span class="pg-badge pg-badge-blue">Intermediate</span></td><td>Complex SPL (eval, rex, transaction, join), lookups, macros, dashboards, alerts</td><td>2-4 weeks</td></tr>
        <tr><td><span class="pg-badge pg-badge-orange">Advanced</span></td><td>Enterprise Security, RBA, data models, CIM, correlation searches, adaptive response</td><td>1-2 months</td></tr>
        <tr><td><span class="pg-badge pg-badge-red">Expert</span></td><td>Custom apps, REST API, KV store, HEC, cluster management, performance tuning</td><td>3-6 months</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── MICROSOFT SENTINEL ──────────────────────────────────────────
richPageContent.sentinel = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">MICROSOFT SENTINEL</h1>
    <span class="card-tag" style="position:static">SIEM</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Cloud-native SIEM + SOAR built on Azure. KQL-powered analytics with native Microsoft 365 integration.</p>

<div class="pg-section">
    <div class="pg-section-title">OVERVIEW</div>
    <p style="color:var(--text-secondary);line-height:1.7;font-size:0.88em">
        Microsoft Sentinel is a cloud-native SIEM and SOAR solution running on Azure. It uses KQL (Kusto Query Language) for detection, hunting, and investigation. Sentinel excels in Microsoft-heavy environments with native connectors for M365, Azure AD, Defender suite, and 200+ third-party data sources. Key advantages: no infrastructure to manage, pay-per-GB pricing, built-in UEBA, and Logic App-based SOAR automation.
    </p>
</div>

<div class="pg-section">
    <div class="pg-section-title">ARCHITECTURE</div>
    <div class="pg-ascii-art"><pre>
    ┌─────────────────────────────────────────────────────────┐
    │                    AZURE CLOUD                          │
    │  ┌──────────┐  ┌──────────┐  ┌──────────┐             │
    │  │ Data      │  │ Log      │  │ Sentinel │             │
    │  │ Connectors│─▶│ Analytics│─▶│ Workspace│             │
    │  │ (200+)    │  │ Workspace│  │          │             │
    │  └──────────┘  └──────────┘  └─────┬────┘             │
    │       ▲                            │                    │
    │  ┌────┴────┐   ┌──────────┐   ┌───▼──────┐            │
    │  │ M365    │   │ Analytics│   │ Incidents│            │
    │  │ Azure AD│   │ Rules    │   │ & Alerts │            │
    │  │ Defender│   │ (KQL)    │   └───┬──────┘            │
    │  │ 3rd Pty │   └──────────┘       │                    │
    │  └─────────┘                 ┌────▼─────┐              │
    │                              │ Logic App│              │
    │                              │ Playbooks│              │
    │                              └──────────┘              │
    └─────────────────────────────────────────────────────────┘
    </pre></div>
</div>

<div class="pg-section">
    <div class="pg-section-title">KQL QUERY ESSENTIALS</div>

    <h4 style="color:#0f0;margin-top:15px">1. Failed Login Detection</h4>
    ${pgCode(`SigninLogs
| where ResultType != "0"
| summarize FailureCount = count(),
    DistinctUsers = dcount(UserPrincipalName),
    Users = make_set(UserPrincipalName, 10)
    by IPAddress, bin(TimeGenerated, 10m)
| where FailureCount > 20 or DistinctUsers > 5
| sort by FailureCount desc`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">2. Suspicious PowerShell</h4>
    ${pgCode(`DeviceProcessEvents
| where FileName in~ ("powershell.exe", "pwsh.exe")
| where ProcessCommandLine has_any ("encodedcommand", "bypass", "hidden", "downloadstring", "iex", "invoke-expression", "frombase64")
| project TimeGenerated, DeviceName, AccountName, ProcessCommandLine, InitiatingProcessFileName
| sort by TimeGenerated desc`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">3. Impossible Travel Detection</h4>
    ${pgCode(`SigninLogs
| where ResultType == "0"
| project TimeGenerated, UserPrincipalName, IPAddress, Location, City = tostring(LocationDetails.city), Country = tostring(LocationDetails.countryOrRegion)
| sort by UserPrincipalName, TimeGenerated asc
| serialize
| extend PrevTime = prev(TimeGenerated), PrevCity = prev(City), PrevCountry = prev(Country), PrevUser = prev(UserPrincipalName)
| where UserPrincipalName == PrevUser
| extend TimeDiffMinutes = datetime_diff('minute', TimeGenerated, PrevTime)
| where TimeDiffMinutes < 60 and City != PrevCity and Country != PrevCountry`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">4. Privilege Escalation Monitoring</h4>
    ${pgCode(`AuditLogs
| where OperationName has_any ("Add member to role", "Add eligible member to role")
| extend TargetUser = tostring(TargetResources[0].userPrincipalName)
| extend RoleName = tostring(TargetResources[0].displayName)
| where RoleName has_any ("Global Administrator", "Security Administrator", "Exchange Administrator")
| project TimeGenerated, InitiatedBy = tostring(InitiatedBy.user.userPrincipalName), TargetUser, RoleName
| sort by TimeGenerated desc`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">5. Data Exfiltration via Email</h4>
    ${pgCode(`EmailEvents
| where SenderFromAddress endswith "@yourdomain.com"
| join kind=inner (
    EmailAttachmentInfo
    | where FileType has_any ("xlsx", "csv", "pdf", "zip", "7z", "rar")
) on NetworkMessageId
| summarize AttachmentCount = count(), TotalSize = sum(FileSize),
    FileTypes = make_set(FileType) by SenderFromAddress, bin(TimeGenerated, 1h)
| where TotalSize > 50000000 or AttachmentCount > 20
| sort by TotalSize desc`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">6. Analytics Rule Template</h4>
    ${pgCode(`// Scheduled Analytics Rule: Suspicious Service Installation
SecurityEvent
| where EventID == 7045
| where ServiceFileName has_any ("powershell", "cmd.exe", "mshta", "rundll32", "regsvr32", "certutil")
    or ServiceFileName matches regex @"\\\\(Temp|tmp|AppData|Downloads)\\\\"
| project TimeGenerated, Computer, ServiceName, ServiceFileName, ServiceStartType, Account
| extend HostName = tostring(split(Computer, ".")[0])`, 'kql')}
</div>

<div class="pg-section">
    <div class="pg-section-title">SENTINEL BEST PRACTICES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Use Content Hub</h4><p>Install solution packs from Content Hub for pre-built analytics rules, hunting queries, workbooks, and playbooks. Saves weeks of setup.</p></div>
        <div class="pg-info-card"><h4>Cost Optimization</h4><p>Use Basic Logs tier for high-volume/low-value data. Set data retention policies. Use Commitment Tiers for predictable pricing above 100GB/day.</p></div>
        <div class="pg-info-card"><h4>UEBA</h4><p>Enable User and Entity Behavior Analytics to detect anomalous behavior like impossible travel, unusual resource access, and lateral movement patterns.</p></div>
        <div class="pg-info-card"><h4>Automation Rules</h4><p>Use automation rules for incident triage — auto-assign, change severity, run playbooks based on conditions. Reduces SOC workload by 40%+.</p></div>
        <div class="pg-info-card"><h4>Watchlists</h4><p>Create watchlists for VIP users, critical assets, known IPs, and IOCs. Reference in KQL with _GetWatchlist('name') for efficient enrichment.</p></div>
        <div class="pg-info-card"><h4>Multi-Workspace</h4><p>Use Azure Lighthouse for MSSP scenarios. Cross-workspace queries with workspace() function. Centralized incident management.</p></div>
    </div>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── IBM QRADAR ──────────────────────────────────────────────────
richPageContent.qradar = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">IBM QRADAR</h1>
    <span class="card-tag" style="position:static">SIEM</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Enterprise SIEM with AQL query language, offense management, and network flow analysis.</p>

<div class="pg-section">
    <div class="pg-section-title">OVERVIEW</div>
    <p style="color:var(--text-secondary);line-height:1.7;font-size:0.88em">
        IBM QRadar is an enterprise SIEM that correlates events and flows to create offenses — prioritized security incidents. It uses AQL (Ariel Query Language) for searching, and provides built-in network flow analysis, vulnerability correlation, and risk scoring. QRadar excels in large-scale environments with complex compliance requirements.
    </p>
</div>

<div class="pg-section">
    <div class="pg-section-title">AQL QUERY EXAMPLES</div>

    <h4 style="color:#0f0;margin-top:15px">1. Failed Logins by Source</h4>
    ${pgCode(`SELECT sourceip, username, COUNT(*) as login_failures
FROM events
WHERE category = 'Authentication'
AND eventdirection = 'L2R'
AND LOGSOURCETYPENAME(logsourceid) = 'Microsoft Windows Security Event Log'
AND "EventID" = '4625'
GROUP BY sourceip, username
HAVING COUNT(*) > 10
ORDER BY login_failures DESC
LAST 1 HOURS`, 'aql')}

    <h4 style="color:#0f0;margin-top:15px">2. Suspicious Process Execution</h4>
    ${pgCode(`SELECT starttime, sourceip, username, "Process Name", "Process CommandLine"
FROM events
WHERE "EventID" IN ('1', '4688')
AND ("Process CommandLine" ILIKE '%encodedcommand%'
    OR "Process CommandLine" ILIKE '%downloadstring%'
    OR "Process CommandLine" ILIKE '%invoke-expression%')
ORDER BY starttime DESC
LAST 24 HOURS`, 'aql')}

    <h4 style="color:#0f0;margin-top:15px">3. Network Flow Anomalies</h4>
    ${pgCode(`SELECT sourceip, destinationip, destinationport, SUM(totalbytessent) as bytes_out
FROM flows
WHERE sourceip INCIDR '10.0.0.0/8'
AND NOT destinationip INCIDR '10.0.0.0/8'
AND destinationport NOT IN (80, 443, 53)
GROUP BY sourceip, destinationip, destinationport
HAVING SUM(totalbytessent) > 100000000
LAST 1 HOURS`, 'aql')}

    <h4 style="color:#0f0;margin-top:15px">4. Lateral Movement Detection</h4>
    ${pgCode(`SELECT sourceip, COUNT(DISTINCT destinationip) as unique_targets,
    GROUP_CONCAT(DISTINCT destinationip) as targets
FROM events
WHERE category = 'Authentication'
AND sourceip INCIDR '10.0.0.0/8'
AND eventdirection = 'L2R'
GROUP BY sourceip
HAVING COUNT(DISTINCT destinationip) > 5
LAST 1 HOURS`, 'aql')}
</div>

<div class="pg-section">
    <div class="pg-section-title">KEY CONCEPTS</div>
    <table class="pg-table">
        <tr><th>Concept</th><th>Description</th></tr>
        <tr><td>Offense</td><td>Correlated security incident combining multiple events/flows. Auto-prioritized by magnitude.</td></tr>
        <tr><td>Log Source</td><td>Configured data input. Each source has a DSM (Device Support Module) for parsing.</td></tr>
        <tr><td>Reference Set</td><td>Dynamic lookup table for IOCs, whitelists, asset info. Used in rules for fast matching.</td></tr>
        <tr><td>Building Block</td><td>Reusable rule component — tests conditions but doesn't create offenses on its own.</td></tr>
        <tr><td>Custom Property</td><td>Extracted field from log data using regex or JSON path.</td></tr>
        <tr><td>Magnitude</td><td>Offense priority score (1-10) calculated from relevance, severity, and credibility.</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── ELASTIC SIEM ────────────────────────────────────────────────
richPageContent.elastic = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">ELASTIC SIEM / SECURITY</h1>
    <span class="card-tag" style="position:static">SIEM</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Open-source SIEM built on Elasticsearch with EQL, KQL, and machine learning detection capabilities.</p>

<div class="pg-section">
    <div class="pg-section-title">OVERVIEW</div>
    <p style="color:var(--text-secondary);line-height:1.7;font-size:0.88em">
        Elastic Security combines SIEM and endpoint security in a single platform built on the Elastic Stack (Elasticsearch, Kibana, Logstash, Beats). It supports three query languages: KQL (Kibana Query Language) for filtering, EQL (Event Query Language) for sequence-based detection, and ES|QL for analytics. The platform includes 700+ pre-built detection rules, ML anomaly detection, and Elastic Agent for unified data collection.
    </p>
</div>

<div class="pg-section">
    <div class="pg-section-title">QUERY EXAMPLES</div>

    <h4 style="color:#0f0;margin-top:15px">1. EQL — Process Injection Sequence</h4>
    ${pgCode(`sequence by host.name with maxspan=1m
  [process where event.type == "start" and process.name == "powershell.exe"]
  [library where dll.name == "amsi.dll" and process.name == "powershell.exe"]
  [process where event.type == "start" and process.parent.name == "powershell.exe"
    and process.name in ("cmd.exe", "whoami.exe", "net.exe")]`, 'eql')}

    <h4 style="color:#0f0;margin-top:15px">2. EQL — Lateral Movement via PsExec</h4>
    ${pgCode(`sequence by host.name with maxspan=5m
  [network where destination.port == 445 and source.ip != "127.0.0.1"]
  [file where file.name : "PSEXESVC.exe"]
  [process where process.parent.name == "PSEXESVC.exe"]`, 'eql')}

    <h4 style="color:#0f0;margin-top:15px">3. KQL — Suspicious DNS</h4>
    ${pgCode(`dns.question.name: *.tk OR dns.question.name: *.top OR dns.question.name: *.xyz
AND NOT dns.question.name: (known-good-domain.com OR microsoft.com)`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">4. Detection Rule (TOML format)</h4>
    ${pgCode(`[rule]
name = "Suspicious PowerShell Encoded Command"
description = "Detects PowerShell with encoded command arguments"
risk_score = 73
severity = "high"
type = "eql"
query = '''
process where event.type == "start" and
  process.name : ("powershell.exe", "pwsh.exe") and
  process.args : ("-enc*", "-EncodedCommand*", "-ec*")
'''

[rule.threat]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
[[rule.threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"`, 'toml')}
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── WAZUH ──────────────────────────────────────────────────────
richPageContent.wazuh = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">WAZUH</h1>
    <span class="card-tag" style="position:static">SIEM/XDR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Open-source unified XDR and SIEM with agent-based endpoint monitoring, FIM, vulnerability detection.</p>

<div class="pg-section">
    <div class="pg-section-title">OVERVIEW</div>
    <p style="color:var(--text-secondary);line-height:1.7;font-size:0.88em">
        Wazuh is a free, open-source security platform that unifies XDR and SIEM capabilities. It deploys lightweight agents on endpoints that monitor file integrity, detect vulnerabilities, assess configuration compliance, and detect threats using XML-based custom rules and decoders. Wazuh integrates natively with Elastic Stack for visualization and with Shuffle SOAR for automation.
    </p>
</div>

<div class="pg-section">
    <div class="pg-section-title">CUSTOM RULE EXAMPLES</div>

    <h4 style="color:#0f0;margin-top:15px">1. Detect Mimikatz Execution</h4>
    ${pgCode(`<group name="custom_threat_detection,">
  <rule id="100100" level="15">
    <if_group>sysmon_event1</if_group>
    <field name="win.eventdata.image" type="pcre2">(?i)mimikatz</field>
    <description>Mimikatz execution detected on $(win.eventdata.computer)</description>
    <mitre>
      <id>T1003</id>
    </mitre>
    <options>alert_by_email</options>
  </rule>

  <rule id="100101" level="14">
    <if_group>sysmon_event1</if_group>
    <field name="win.eventdata.commandLine" type="pcre2">(?i)(sekurlsa|lsadump|kerberos::list|crypto::certificates)</field>
    <description>Credential dumping tool arguments detected</description>
    <mitre>
      <id>T1003.001</id>
    </mitre>
  </rule>
</group>`, 'xml')}

    <h4 style="color:#0f0;margin-top:15px">2. File Integrity Monitoring Alert</h4>
    ${pgCode(`<group name="custom_fim,">
  <rule id="100200" level="12">
    <if_sid>550</if_sid>
    <field name="file">/etc/passwd|/etc/shadow|/etc/sudoers</field>
    <description>Critical system file modified: $(file)</description>
    <mitre>
      <id>T1098</id>
    </mitre>
  </rule>
</group>`, 'xml')}

    <h4 style="color:#0f0;margin-top:15px">3. Active Response — Block IP</h4>
    ${pgCode(`<!-- ossec.conf -->
<active-response>
  <command>firewall-drop</command>
  <location>local</location>
  <rules_id>100100,100101</rules_id>
  <timeout>3600</timeout>
</active-response>`, 'xml')}
</div>

<div class="pg-section">
    <div class="pg-section-title">KEY CAPABILITIES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>File Integrity Monitoring</h4><p>Real-time monitoring of file/registry changes with who-data (who changed what). Critical for compliance (PCI-DSS, HIPAA).</p></div>
        <div class="pg-info-card"><h4>Vulnerability Detection</h4><p>Agent-based vulnerability scanning using NVD, OVAL, and vendor advisories. No network scanning needed.</p></div>
        <div class="pg-info-card"><h4>Configuration Assessment</h4><p>CIS benchmark checks for Windows, Linux, macOS. Automatic scoring and remediation guidance.</p></div>
        <div class="pg-info-card"><h4>Active Response</h4><p>Automated response: block IPs, kill processes, disable accounts, quarantine files. Configurable per rule.</p></div>
        <div class="pg-info-card"><h4>Custom Decoders</h4><p>Parse any log format with XML decoders. Extract fields using regex. Chain decoders for complex formats.</p></div>
        <div class="pg-info-card"><h4>Sysmon Integration</h4><p>Full Sysmon event parsing (Event ID 1-26). Pre-built rules for process creation, network, file, registry events.</p></div>
    </div>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── MICROSOFT DEFENDER FOR ENDPOINT ─────────────────────────────
richPageContent.mde = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">MICROSOFT DEFENDER FOR ENDPOINT</h1>
    <span class="card-tag" style="position:static">EDR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Microsoft's EDR solution with Advanced Hunting (KQL), ASR rules, automated investigation.</p>

<div class="pg-section">
    <div class="pg-section-title">ADVANCED HUNTING QUERIES</div>

    <h4 style="color:#0f0;margin-top:15px">1. Credential Dumping Detection</h4>
    ${pgCode(`DeviceProcessEvents
| where FileName in~ ("procdump.exe", "procdump64.exe", "mimikatz.exe")
    or (FileName =~ "rundll32.exe" and ProcessCommandLine has "comsvcs.dll")
    or ProcessCommandLine has_any ("sekurlsa", "lsadump", "MiniDump")
| project Timestamp, DeviceName, AccountName, FileName, ProcessCommandLine, InitiatingProcessFileName
| sort by Timestamp desc`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">2. Ransomware Indicators</h4>
    ${pgCode(`DeviceFileEvents
| where Timestamp > ago(1h)
| where ActionType == "FileRenamed"
| extend FileExtension = tostring(split(FileName, ".")[-1])
| where FileExtension in ("encrypted", "locked", "crypt", "enc", "cry", "crypto")
| summarize RenamedFiles = count(),
    UniqueExtensions = dcount(FileExtension),
    Devices = make_set(DeviceName)
    by InitiatingProcessFileName, bin(Timestamp, 5m)
| where RenamedFiles > 50`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">3. Persistence via Scheduled Tasks</h4>
    ${pgCode(`DeviceProcessEvents
| where FileName =~ "schtasks.exe"
| where ProcessCommandLine has "/create"
| where ProcessCommandLine has_any ("/sc minute", "/sc hourly", "/sc onlogon", "/sc onstart")
| where InitiatingProcessFileName !in~ ("svchost.exe", "msiexec.exe", "setup.exe")
| project Timestamp, DeviceName, AccountName, ProcessCommandLine
| sort by Timestamp desc`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">4. Custom Detection Rule Template</h4>
    ${pgCode(`// Custom detection: LOLBin execution from user directories
DeviceProcessEvents
| where Timestamp > ago(1h)
| where FileName in~ ("certutil.exe", "mshta.exe", "regsvr32.exe", "rundll32.exe", "bitsadmin.exe")
| where FolderPath has_any ("\\\\Users\\\\", "\\\\Temp\\\\", "\\\\Downloads\\\\", "\\\\AppData\\\\")
| project Timestamp, DeviceName, AccountName, FileName, ProcessCommandLine, FolderPath
// Save as Custom Detection > Set frequency to every hour > Action: Alert + Isolate device`, 'kql')}
</div>

<div class="pg-section">
    <div class="pg-section-title">ASR RULES (Attack Surface Reduction)</div>
    <table class="pg-table">
        <tr><th>Rule</th><th>GUID</th><th>Impact</th></tr>
        <tr><td>Block Office from creating child processes</td><td>D4F940AB-401B-4EFC-AADC-AD5F3C50688A</td><td>Blocks macro-based attacks</td></tr>
        <tr><td>Block credential stealing from LSASS</td><td>9E6C4E1F-7D60-472F-BA1A-A39EF669E4B2</td><td>Prevents Mimikatz-like tools</td></tr>
        <tr><td>Block process creations from WMI/PSExec</td><td>D1E49AAC-8F56-4280-B9BA-993A6D77406C</td><td>Stops lateral movement</td></tr>
        <tr><td>Block executable content from email</td><td>BE9BA2D9-53EA-4CDC-84E5-9B1EEEE46550</td><td>Email-borne malware prevention</td></tr>
        <tr><td>Block untrusted/unsigned processes from USB</td><td>B2B3F03D-6A65-4F7B-A9C7-1C7EF74A9BA4</td><td>USB-based attack prevention</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── SENTINELONE ────────────────────────────────────────────────
richPageContent.sentinelone = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">SENTINELONE</h1>
    <span class="card-tag" style="position:static">EDR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Autonomous AI-driven endpoint protection with Storyline technology and Deep Visibility queries.</p>

<div class="pg-section">
    <div class="pg-section-title">DEEP VISIBILITY QUERIES</div>

    <h4 style="color:#0f0;margin-top:15px">1. Ransomware File Encryption</h4>
    ${pgCode(`ObjectType = "File" AND EventType = "Modified Rename"
AND TgtFileExtension In Contains AnyCase ("encrypted","locked","crypt","ransom")
AND SrcProcName NOT In AnyCase ("explorer.exe","rename.exe")`, 'sql')}

    <h4 style="color:#0f0;margin-top:15px">2. LOLBin Abuse</h4>
    ${pgCode(`ObjectType = "Process" AND EventType = "Process Creation"
AND (TgtProcName In AnyCase ("certutil.exe","mshta.exe","regsvr32.exe","bitsadmin.exe"))
AND TgtProcCmdLine ContainsCIS ("http" OR "ftp" OR "download" OR "transfer")`, 'sql')}

    <h4 style="color:#0f0;margin-top:15px">3. STAR Rule (Custom Detection)</h4>
    ${pgCode(`{
  "name": "Suspicious PowerShell Download Cradle",
  "queryType": "events",
  "query": "ObjectType = \\"Process\\" AND TgtProcName = \\"powershell.exe\\" AND TgtProcCmdLine RegExp \\"(New-Object|WebClient|DownloadString|DownloadFile|Invoke-WebRequest|wget|curl)\\"",
  "severity": "High",
  "status": true,
  "networkQuarantine": false,
  "treatAsThreat": "Suspicious"
}`, 'json')}
</div>

<div class="pg-section">
    <div class="pg-section-title">KEY FEATURES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Storyline</h4><p>Auto-correlates all related events into attack storylines — see the full kill chain from initial access to impact in one view.</p></div>
        <div class="pg-info-card"><h4>Rollback</h4><p>Windows VSS-based ransomware rollback. Revert encrypted files to pre-attack state with one click.</p></div>
        <div class="pg-info-card"><h4>Remote Shell</h4><p>Full remote shell access to endpoints for investigation and remediation — PowerShell, Bash, or Python.</p></div>
        <div class="pg-info-card"><h4>Ranger (Network Discovery)</h4><p>Discover and fingerprint all network devices including IoT/OT. Identify unmanaged endpoints.</p></div>
    </div>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── CARBON BLACK ───────────────────────────────────────────────
richPageContent.carbonblack = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">VMWARE CARBON BLACK</h1>
    <span class="card-tag" style="position:static">EDR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Endpoint detection with Cb Response (EDR) and Cb Defense (NGAV). Watchlist-based detection.</p>

<div class="pg-section">
    <div class="pg-section-title">WATCHLIST QUERIES</div>

    <h4 style="color:#0f0;margin-top:15px">1. Ransomware Behavior</h4>
    ${pgCode(`(process_name:vssadmin.exe AND cmdline:"delete shadows") OR
(process_name:wmic.exe AND cmdline:"shadowcopy delete") OR
(process_name:bcdedit.exe AND cmdline:"recoveryenabled no") OR
(filemod_count:[100 TO *] AND process_name:* AND -process_publisher_state:FILE_SIGNATURE_STATE_SIGNED)`, 'text')}

    <h4 style="color:#0f0;margin-top:15px">2. Living Off the Land</h4>
    ${pgCode(`(process_name:certutil.exe AND (cmdline:"-urlcache" OR cmdline:"-decode" OR cmdline:"-encode")) OR
(process_name:bitsadmin.exe AND cmdline:"/transfer") OR
(process_name:mshta.exe AND cmdline:"http")`, 'text')}
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── CORTEX XDR ─────────────────────────────────────────────────
richPageContent.cortex = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">PALO ALTO CORTEX XDR</h1>
    <span class="card-tag" style="position:static">XDR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Extended detection and response with XQL queries, BIOC rules, and cross-data-source correlation.</p>

<div class="pg-section">
    <div class="pg-section-title">XQL QUERY EXAMPLES</div>

    <h4 style="color:#0f0;margin-top:15px">1. Process Chain Analysis</h4>
    ${pgCode(`dataset = xdr_data
| filter event_type = ENUM.PROCESS and action_process_image_name in ("cmd.exe","powershell.exe")
| filter action_process_image_command_line contains "encodedcommand" or action_process_image_command_line contains "bypass"
| fields agent_hostname, actor_process_image_name, action_process_image_name, action_process_image_command_line, _time
| sort desc _time`, 'xql')}

    <h4 style="color:#0f0;margin-top:15px">2. Lateral Movement via RDP</h4>
    ${pgCode(`dataset = xdr_data
| filter event_type = ENUM.NETWORK and action_remote_port = 3389
| comp count(agent_hostname) as connection_count by action_remote_ip
| filter connection_count > 5
| sort desc connection_count`, 'xql')}

    <h4 style="color:#0f0;margin-top:15px">3. BIOC Rule Template</h4>
    ${pgCode(`{
  "name": "Suspicious LSASS Access",
  "description": "Detects processes accessing LSASS memory for credential dumping",
  "severity": "HIGH",
  "ioc_type": "BIOC",
  "indicator": {
    "type": "process",
    "filter": {
      "AND": [
        {"field": "target_process_image_name", "value": "lsass.exe"},
        {"field": "actor_process_image_name", "NOT_IN": ["svchost.exe", "lsm.exe", "csrss.exe"]}
      ]
    }
  },
  "mitre_tactics": ["TA0006"],
  "mitre_techniques": ["T1003.001"]
}`, 'json')}
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── MICROSOFT 365 DEFENDER ─────────────────────────────────────
richPageContent.m365 = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">MICROSOFT 365 DEFENDER</h1>
    <span class="card-tag" style="position:static">XDR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Unified XDR across endpoints, email, identity, and cloud apps. Cross-workload KQL hunting.</p>

<div class="pg-section">
    <div class="pg-section-title">CROSS-WORKLOAD HUNTING QUERIES</div>

    <h4 style="color:#0f0;margin-top:15px">1. Phishing to Credential Theft Chain</h4>
    ${pgCode(`// Find emails with links → user clicked → suspicious sign-in
EmailUrlInfo
| where Url has_any ("login", "signin", "verify", "update-account")
| join kind=inner EmailEvents on NetworkMessageId
| where DeliveryAction == "Delivered"
| join kind=inner (
    IdentityLogonEvents
    | where LogonType == "Interactive" and ActionType == "LogonSuccess"
    | where Timestamp > ago(2h)
) on $left.RecipientEmailAddress == $right.AccountUpn
| project EmailTimestamp = Timestamp, Recipient = RecipientEmailAddress, PhishUrl = Url, LogonTime = Timestamp1, LogonIP = IPAddress`, 'kql')}

    <h4 style="color:#0f0;margin-top:15px">2. BEC (Business Email Compromise)</h4>
    ${pgCode(`// Detect inbox rule creation after suspicious sign-in
IdentityLogonEvents
| where ActionType == "LogonSuccess"
| where ISP != "Microsoft Azure" and Country != "US" // adjust for your org
| join kind=inner (
    CloudAppEvents
    | where ActionType == "New-InboxRule"
    | extend RuleName = tostring(RawEventData.Parameters[0].Value)
) on AccountObjectId
| project LogonTime = Timestamp, Account = AccountUpn, LogonIP = IPAddress, LogonCountry = Country, RuleCreated = RuleName`, 'kql')}
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── SOAR PLATFORMS ─────────────────────────────────────────────

richPageContent.splunksoar = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">SPLUNK SOAR (PHANTOM)</h1>
    <span class="card-tag" style="position:static">SOAR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Industry-leading SOAR with visual playbook editor, 400+ app integrations, and Python custom functions.</p>

<div class="pg-section">
    <div class="pg-section-title">OVERVIEW</div>
    <p style="color:var(--text-secondary);line-height:1.7;font-size:0.88em">
        Splunk SOAR (formerly Phantom) enables security teams to automate repetitive tasks, orchestrate tools, and respond to threats faster. Playbooks can be created visually or in Python. The platform integrates with 400+ security tools and can process thousands of events per hour.
    </p>
</div>

<div class="pg-section">
    <div class="pg-section-title">PLAYBOOK EXAMPLE — Phishing Response</div>
    ${pgCode(`import phantom.rules as phantom
import json

def on_start(container):
    # Extract artifacts from phishing email
    phantom.act("extract ioc", parameters=[{"input_string": container["data"]["raw_email"]}],
                callback=ioc_extracted)

def ioc_extracted(action, success, container, results, handle):
    if not success:
        return
    # Check reputation of extracted IOCs
    for result in results:
        if result.get("url"):
            phantom.act("url reputation", parameters=[{"url": result["url"]}],
                        assets=["virustotal"], callback=reputation_check)
        if result.get("ip"):
            phantom.act("ip reputation", parameters=[{"ip": result["ip"]}],
                        assets=["virustotal"], callback=reputation_check)

def reputation_check(action, success, container, results, handle):
    for result in results:
        if result.get("summary", {}).get("positives", 0) > 3:
            # Malicious — block and notify
            phantom.act("block url", parameters=[{"url": result["url"]}],
                        assets=["firewall"])
            phantom.act("send email", parameters=[{
                "to": "soc-team@company.com",
                "subject": f"ALERT: Malicious phishing detected",
                "body": f"Blocked malicious URL: {result['url']}"
            }], assets=["smtp"])`, 'python')}
</div>

<div class="pg-section">
    <div class="pg-section-title">KEY CONCEPTS</div>
    <table class="pg-table">
        <tr><th>Concept</th><th>Description</th></tr>
        <tr><td>Playbook</td><td>Automated workflow — visual (drag-drop) or Python code. Triggered by events or manually.</td></tr>
        <tr><td>App</td><td>Integration connector to external tool (VirusTotal, Firewall, SIEM, Ticketing).</td></tr>
        <tr><td>Asset</td><td>Configured instance of an app with credentials and connection details.</td></tr>
        <tr><td>Container</td><td>Security event or incident that triggers playbook execution.</td></tr>
        <tr><td>Artifact</td><td>IOC or data element within a container (IP, URL, hash, email).</td></tr>
        <tr><td>Custom Function</td><td>Reusable Python function available to all playbooks.</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.xsoar = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">PALO ALTO XSOAR</h1>
    <span class="card-tag" style="position:static">SOAR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Cortex XSOAR — SOAR platform with 700+ integrations, War Room collaboration, and ML-powered insights.</p>

<div class="pg-section">
    <div class="pg-section-title">PLAYBOOK YAML EXAMPLE</div>
    ${pgCode(`id: Phishing Investigation
name: Phishing Investigation
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: extract_indicators
    type: playbook
    name: Extract Indicators
    scriptName: ExtractIndicatorsFromEmail
  "1":
    id: "1"
    taskid: enrich_indicators
    type: playbook
    name: Enrich Indicators
    scriptName: IndicatorEnrichment
    dependsOn: ["0"]
  "2":
    id: "2"
    taskid: analyst_review
    type: condition
    name: Is Malicious?
    conditions:
      - label: "yes"
        condition:
          - - operator: greaterThan
              left: indicator.score
              right: 2
      - label: "no"
    dependsOn: ["1"]
  "3":
    id: "3"
    taskid: block_indicators
    type: playbook
    name: Block Indicators
    scriptName: BlockIndicators
    dependsOn:
      "2": ["yes"]`, 'yaml')}
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.sentinelsoar = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">MICROSOFT SENTINEL SOAR</h1>
    <span class="card-tag" style="position:static">SOAR</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">Logic App-based automation for Sentinel incidents — built natively into Azure.</p>

<div class="pg-section">
    <div class="pg-section-title">AUTOMATION CAPABILITIES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Automation Rules</h4><p>Lightweight rules that auto-assign, change severity, add tags, or run playbooks when incidents are created.</p></div>
        <div class="pg-info-card"><h4>Logic App Playbooks</h4><p>Full automation workflows triggered by Sentinel incidents. 300+ connectors available (Teams, ServiceNow, etc.).</p></div>
        <div class="pg-info-card"><h4>Incident Triggers</h4><p>Playbooks trigger on incident creation, update, or alert creation. Access all incident entities and metadata.</p></div>
        <div class="pg-info-card"><h4>Entity Enrichment</h4><p>Auto-enrich IPs with geolocation, users with AAD info, hosts with Defender data before analyst review.</p></div>
    </div>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// ─── BLUE TEAM RESOURCES ────────────────────────────────────────

richPageContent.detection = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">DETECTION ENGINEERING GUIDE</h1>
    <span class="card-tag" style="position:static">BLUE TEAM</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">DETECTION-AS-CODE PIPELINE</div>
    <div class="pg-ascii-art"><pre>
    ┌──────────┐    ┌──────────┐    ┌──────────┐    ┌──────────┐    ┌──────────┐
    │  WRITE   │───▶│  TEST    │───▶│  REVIEW  │───▶│  DEPLOY  │───▶│  MONITOR │
    │  ──────  │    │  ──────  │    │  ──────  │    │  ──────  │    │  ──────  │
    │  Sigma   │    │  Atomic  │    │  PR +    │    │  CI/CD   │    │  FP Rate │
    │  Format  │    │  Red Team│    │  Peer    │    │  Push to │    │  TP Rate │
    │  Git Repo│    │  Validate│    │  Review  │    │  SIEM    │    │  Tune    │
    └──────────┘    └──────────┘    └──────────┘    └──────────┘    └──────────┘
    </pre></div>
</div>

<div class="pg-section">
    <div class="pg-section-title">SIGMA RULE TEMPLATE</div>
    ${pgCode(`title: Suspicious PowerShell Encoded Command
id: a1b2c3d4-e5f6-7890-abcd-ef1234567890
status: experimental
description: Detects PowerShell with encoded command arguments
author: BlueShell SOC
date: 2024/01/15
modified: 2024/06/01
tags:
    - attack.execution
    - attack.t1059.001
    - attack.defense_evasion
    - attack.t1027
logsource:
    category: process_creation
    product: windows
detection:
    selection_process:
        Image|endswith:
            - '\\powershell.exe'
            - '\\pwsh.exe'
    selection_encoded:
        CommandLine|contains:
            - '-enc'
            - '-EncodedCommand'
            - '-ec '
    condition: selection_process and selection_encoded
falsepositives:
    - Legitimate admin scripts using encoded commands
    - SCCM/Intune deployments
    - Configuration management tools
level: high`, 'yaml')}
</div>

<div class="pg-section">
    <div class="pg-section-title">DETECTION MATURITY MODEL</div>
    <table class="pg-table">
        <tr><th>Level</th><th>Name</th><th>Description</th></tr>
        <tr><td>0</td><td>None</td><td>No detection capability. Relying on vendor defaults.</td></tr>
        <tr><td>1</td><td>Reactive</td><td>Basic vendor rules enabled. Alert on known-bad IOCs. Manual triage.</td></tr>
        <tr><td>2</td><td>Proactive</td><td>Custom rules for org-specific threats. Sigma format. Some automation.</td></tr>
        <tr><td>3</td><td>Managed</td><td>Detection-as-code pipeline. Automated testing. Coverage tracking vs MITRE.</td></tr>
        <tr><td>4</td><td>Optimized</td><td>ML-assisted detection. Continuous tuning. Red team validated. <5% FP rate.</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.ir = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">INCIDENT RESPONSE PLAYBOOKS</h1>
    <span class="card-tag" style="position:static">BLUE TEAM</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">NIST INCIDENT RESPONSE LIFECYCLE</div>
    <div class="pg-ascii-art"><pre>
    ┌──────────────┐    ┌──────────────┐    ┌──────────────┐    ┌──────────────┐
    │ PREPARATION  │───▶│  DETECTION   │───▶│ CONTAINMENT  │───▶│  RECOVERY    │
    │              │    │  & ANALYSIS  │    │  ERADICATION │    │  & LESSONS   │
    │ Tools, team, │    │ Alerts, IOCs │    │ Isolate,     │    │ Restore,     │
    │ runbooks,    │    │ triage,      │    │ block, wipe, │    │ verify,      │
    │ training     │    │ investigate  │    │ remove root  │    │ document,    │
    │              │    │              │    │ cause        │    │ improve      │
    └──────────────┘    └──────────────┘    └──────────────┘    └──────────────┘
    </pre></div>
</div>

<div class="pg-section">
    <div class="pg-section-title">PLAYBOOK QUICK REFERENCE</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>1. Phishing Response</h4><p><strong>Contain:</strong> Delete email from all inboxes, block sender domain. <strong>Investigate:</strong> Check who clicked, extract IOCs. <strong>Remediate:</strong> Reset compromised passwords, scan endpoints.</p></div>
        <div class="pg-info-card"><h4>2. Ransomware Response</h4><p><strong>Contain:</strong> Isolate affected hosts immediately, disable network shares. <strong>Investigate:</strong> Identify patient zero, determine encryption scope. <strong>Recover:</strong> Restore from clean backups, rebuild if needed.</p></div>
        <div class="pg-info-card"><h4>3. Data Breach Response</h4><p><strong>Contain:</strong> Revoke access, block exfil channels. <strong>Investigate:</strong> Determine what data was accessed/exfiltrated. <strong>Report:</strong> Legal notification within 72 hours (GDPR), breach notification.</p></div>
        <div class="pg-info-card"><h4>4. Insider Threat</h4><p><strong>Contain:</strong> Disable account, preserve evidence. <strong>Investigate:</strong> DLP logs, email activity, file access audit. <strong>Coordinate:</strong> HR, Legal, Management involvement required.</p></div>
        <div class="pg-info-card"><h4>5. DDoS Response</h4><p><strong>Contain:</strong> Engage CDN/WAF, rate limiting, geo-blocking. <strong>Investigate:</strong> Identify attack type (volumetric, protocol, application). <strong>Mitigate:</strong> ISP null-route, scrubbing service activation.</p></div>
        <div class="pg-info-card"><h4>6. Supply Chain Compromise</h4><p><strong>Contain:</strong> Block compromised software/update, isolate affected systems. <strong>Investigate:</strong> Identify scope of compromise, check for backdoors. <strong>Recover:</strong> Roll back to clean version, enhanced monitoring.</p></div>
    </div>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.triage = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">ALERT TRIAGE FRAMEWORK</h1>
    <span class="card-tag" style="position:static">BLUE TEAM</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">5-MINUTE TRIAGE METHODOLOGY</div>
    <div class="pg-step"><div class="pg-step-num">1</div><div class="pg-step-text"><strong>CONTEXT (30s):</strong> What rule fired? What MITRE technique? What's the severity? Has this alert fired before?</div></div>
    <div class="pg-step"><div class="pg-step-num">2</div><div class="pg-step-text"><strong>SOURCE (60s):</strong> What host/user triggered it? Is this a critical asset or VIP? What's the asset's risk profile?</div></div>
    <div class="pg-step"><div class="pg-step-num">3</div><div class="pg-step-text"><strong>EVIDENCE (90s):</strong> Look at the raw log. Does the evidence match the rule logic? Check for obvious false positives (admin activity, known tool, scheduled task).</div></div>
    <div class="pg-step"><div class="pg-step-num">4</div><div class="pg-step-text"><strong>ENRICHMENT (60s):</strong> Check IOC reputation (VirusTotal, AbuseIPDB). Check user's recent activity. Check if there are related alerts.</div></div>
    <div class="pg-step"><div class="pg-step-num">5</div><div class="pg-step-text"><strong>DECISION (60s):</strong> True Positive → Escalate to Incident. False Positive → Tune rule. Benign True Positive → Document exception.</div></div>
</div>

<div class="pg-section">
    <div class="pg-section-title">SEVERITY MATRIX</div>
    <table class="pg-table">
        <tr><th>Severity</th><th>Response SLA</th><th>Examples</th><th>Action</th></tr>
        <tr><td><span class="pg-badge pg-badge-red">Critical</span></td><td>15 minutes</td><td>Active ransomware, confirmed breach, C2 callback</td><td>Immediate containment, page on-call, war room</td></tr>
        <tr><td><span class="pg-badge pg-badge-orange">High</span></td><td>1 hour</td><td>Credential theft, lateral movement, data exfil attempt</td><td>Investigate + contain within SLA, notify management</td></tr>
        <tr><td><span class="pg-badge pg-badge-blue">Medium</span></td><td>4 hours</td><td>Suspicious process, policy violation, recon activity</td><td>Investigate during shift, triage and assign</td></tr>
        <tr><td><span class="pg-badge pg-badge-green">Low</span></td><td>24 hours</td><td>Info-level alerts, compliance checks, scan activity</td><td>Batch review, auto-close if benign pattern</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.hunting = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">THREAT HUNTING PLAYBOOKS</h1>
    <span class="card-tag" style="position:static">BLUE TEAM</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">HYPOTHESIS-DRIVEN HUNTING</div>
    <div class="pg-grid">
        <div class="pg-info-card">
            <h4>Hunt 1: Persistence via Scheduled Tasks</h4>
            <p><strong>Hypothesis:</strong> Attackers are using scheduled tasks for persistence.</p>
            <p><strong>Data:</strong> Sysmon Event ID 1 (process), Windows Event 4698</p>
            <p><strong>SPL:</strong> <code>index=wineventlog EventCode=4698 | search TaskName!="\\Microsoft\\*"</code></p>
        </div>
        <div class="pg-info-card">
            <h4>Hunt 2: DNS Tunneling</h4>
            <p><strong>Hypothesis:</strong> C2 or exfil via DNS queries with encoded data.</p>
            <p><strong>Data:</strong> DNS logs, Sysmon Event ID 22</p>
            <p><strong>SPL:</strong> <code>index=dns | eval len=len(query) | where len>50 | stats count by src_ip, query</code></p>
        </div>
        <div class="pg-info-card">
            <h4>Hunt 3: Living Off the Land</h4>
            <p><strong>Hypothesis:</strong> Attackers using LOLBins (certutil, mshta, etc.).</p>
            <p><strong>Data:</strong> Process creation events</p>
            <p><strong>KQL:</strong> <code>DeviceProcessEvents | where FileName in~("certutil.exe","mshta.exe","regsvr32.exe")</code></p>
        </div>
        <div class="pg-info-card">
            <h4>Hunt 4: Kerberoasting</h4>
            <p><strong>Hypothesis:</strong> Attackers requesting TGS tickets for service accounts.</p>
            <p><strong>Data:</strong> Windows Event 4769</p>
            <p><strong>SPL:</strong> <code>index=wineventlog EventCode=4769 TicketEncryptionType=0x17 | stats count by ServiceName, TargetUserName</code></p>
        </div>
    </div>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.runbooks = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">SOC RUNBOOKS</h1>
    <span class="card-tag" style="position:static">BLUE TEAM</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">DAILY SOC OPERATIONS</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Shift Start Checklist</h4>
            <ul><li>Review shift handoff notes</li><li>Check pending incidents queue</li><li>Verify all data sources are ingesting</li><li>Check SIEM health dashboards</li><li>Review overnight critical alerts</li><li>Update SOC channel status</li></ul>
        </div>
        <div class="pg-info-card"><h4>Escalation Procedures</h4>
            <ul><li>L1 → L2: After 15 min investigation, if complex</li><li>L2 → L3: Confirmed incident requiring forensics</li><li>L3 → CIRT: Active breach, executive involvement</li><li>Any level → Management: Data breach, ransomware, media</li></ul>
        </div>
        <div class="pg-info-card"><h4>Communication Templates</h4>
            <ul><li>Initial alert notification (Slack/Teams)</li><li>Incident status update (every 30 min for critical)</li><li>Executive summary (non-technical)</li><li>All-clear notification</li><li>Post-incident report template</li></ul>
        </div>
        <div class="pg-info-card"><h4>KPI Tracking</h4>
            <ul><li>MTTD (Mean Time to Detect) target: &lt;5 min</li><li>MTTR (Mean Time to Respond) target: &lt;30 min</li><li>False Positive Rate target: &lt;30%</li><li>Alert-to-Incident ratio</li><li>Analyst alerts/day capacity: 50-80</li></ul>
        </div>
    </div>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.fetcher = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">THREAT INTEL AUTO-FETCHER</h1>
    <span class="card-tag" style="position:static">TOOL</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">USAGE</div>
    ${pgCode(`# Install dependencies
pip install -r tools/requirements.txt

# Fetch all feeds
python tools/threat-intel-fetcher.py --all

# Fetch specific feeds
python tools/threat-intel-fetcher.py --feeds urlhaus,malwarebazaar,threatfox

# Output in STIX format
python tools/threat-intel-fetcher.py --all --format stix2

# Generate SIEM rules from fetched IOCs
python tools/siem-rule-generator.py --input output/iocs.json --platforms splunk,sentinel,qradar`, 'bash')}
</div>

<div class="pg-section">
    <div class="pg-section-title">SUPPORTED FEEDS</div>
    <table class="pg-table">
        <tr><th>Feed</th><th>IOC Types</th><th>Update Frequency</th></tr>
        <tr><td>abuse.ch URLhaus</td><td>Malicious URLs</td><td>Every 5 minutes</td></tr>
        <tr><td>abuse.ch MalwareBazaar</td><td>Malware hashes (SHA256, MD5)</td><td>Hourly</td></tr>
        <tr><td>abuse.ch ThreatFox</td><td>IPs, domains, URLs, hashes</td><td>Hourly</td></tr>
        <tr><td>abuse.ch FeodoTracker</td><td>Botnet C2 IPs</td><td>Every 30 minutes</td></tr>
        <tr><td>AlienVault OTX</td><td>IPs, domains, URLs, hashes</td><td>Real-time</td></tr>
        <tr><td>MITRE ATT&CK</td><td>Technique/tactic mappings</td><td>Quarterly</td></tr>
        <tr><td>NIST NVD</td><td>CVE vulnerability data</td><td>Daily</td></tr>
        <tr><td>CISA KEV</td><td>Known exploited vulnerabilities</td><td>Weekly</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.ioc = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">IOC MANAGEMENT</h1>
    <span class="card-tag" style="position:static">TOOLS</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">IOC LIFECYCLE</div>
    <div class="pg-ascii-art"><pre>
    COLLECT ──▶ NORMALIZE ──▶ ENRICH ──▶ STORE ──▶ DISTRIBUTE ──▶ AGE/RETIRE
       │           │            │          │           │              │
    OSINT      De-dupe      VT/MISP    STIX 2.1    Push to       30/60/90
    Feeds      Validate     Context    Database    SIEM/EDR      day expiry
    Manual     TLP tag      Scoring    CSV/JSON    IOC feeds     Re-validate
    </pre></div>
</div>

<div class="pg-section">
    <div class="pg-section-title">IOC TYPES & PLATFORMS</div>
    <table class="pg-table">
        <tr><th>IOC Type</th><th>Examples</th><th>Where to Block</th></tr>
        <tr><td>IP Address</td><td>C2 servers, scanners</td><td>Firewall, SIEM watchlist, EDR IOC feed</td></tr>
        <tr><td>Domain</td><td>Phishing, DGA, C2</td><td>DNS sinkhole, web proxy, SIEM</td></tr>
        <tr><td>URL</td><td>Malware download, phishing</td><td>Web proxy, email gateway, browser extension</td></tr>
        <tr><td>File Hash</td><td>Malware SHA256/MD5</td><td>EDR block list, SIEM alert, email gateway</td></tr>
        <tr><td>Email Address</td><td>Phishing sender</td><td>Email gateway block, SIEM watchlist</td></tr>
        <tr><td>Certificate</td><td>Malicious SSL certs</td><td>Web proxy, firewall SSL inspection</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.mitre = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">MITRE ATT&CK NAVIGATOR</h1>
    <span class="card-tag" style="position:static">TOOLS</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">ENTERPRISE TACTICS (14)</div>
    <table class="pg-table">
        <tr><th>ID</th><th>Tactic</th><th>Description</th><th>Coverage</th></tr>
        <tr><td>TA0043</td><td>Reconnaissance</td><td>Gathering information for planning attacks</td><td><span class="pg-badge pg-badge-green">89%</span></td></tr>
        <tr><td>TA0001</td><td>Initial Access</td><td>Getting into the network (phishing, exploit, supply chain)</td><td><span class="pg-badge pg-badge-green">89%</span></td></tr>
        <tr><td>TA0002</td><td>Execution</td><td>Running malicious code (PowerShell, scripts, exploits)</td><td><span class="pg-badge pg-badge-blue">69%</span></td></tr>
        <tr><td>TA0003</td><td>Persistence</td><td>Maintaining foothold (scheduled tasks, registry, services)</td><td><span class="pg-badge pg-badge-orange">42%</span></td></tr>
        <tr><td>TA0004</td><td>Privilege Escalation</td><td>Gaining higher-level permissions</td><td><span class="pg-badge pg-badge-orange">38%</span></td></tr>
        <tr><td>TA0005</td><td>Defense Evasion</td><td>Avoiding detection (obfuscation, disabling tools)</td><td><span class="pg-badge pg-badge-red">19%</span></td></tr>
        <tr><td>TA0006</td><td>Credential Access</td><td>Stealing credentials (dumping, keylogging, phishing)</td><td><span class="pg-badge pg-badge-blue">56%</span></td></tr>
        <tr><td>TA0007</td><td>Discovery</td><td>Learning about the environment (network, users, shares)</td><td><span class="pg-badge pg-badge-red">19%</span></td></tr>
        <tr><td>TA0008</td><td>Lateral Movement</td><td>Moving through the network (RDP, PsExec, WMI)</td><td><span class="pg-badge pg-badge-blue">67%</span></td></tr>
        <tr><td>TA0009</td><td>Collection</td><td>Gathering target data (screenshots, keylogging, email)</td><td><span class="pg-badge pg-badge-orange">29%</span></td></tr>
        <tr><td>TA0010</td><td>Exfiltration</td><td>Stealing data (HTTP, DNS, cloud storage, physical)</td><td><span class="pg-badge pg-badge-blue">56%</span></td></tr>
        <tr><td>TA0011</td><td>Command & Control</td><td>Communicating with compromised systems</td><td><span class="pg-badge pg-badge-orange">44%</span></td></tr>
        <tr><td>TA0040</td><td>Impact</td><td>Disrupting availability (ransomware, wiper, DoS)</td><td><span class="pg-badge pg-badge-orange">33%</span></td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.usecases = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">DETECTION USE CASE LIBRARY</h1>
    <span class="card-tag" style="position:static">BLUE TEAM</span>
</div>
<p style="color:var(--text-secondary);font-size:13px;margin-bottom:20px">100+ detection use cases mapped to MITRE ATT&CK with multi-platform queries. Use the SOC Knowledge Base for full rule details.</p>

<div class="pg-section">
    <div class="pg-section-title">USE CASES BY MITRE TACTIC</div>
    <table class="pg-table">
        <tr><th>Tactic</th><th>Key Use Cases</th><th>Data Sources</th></tr>
        <tr><td>Initial Access</td><td>Phishing link click, Macro execution, Exploit attempt</td><td>Email, Web Proxy, IDS/IPS</td></tr>
        <tr><td>Execution</td><td>PowerShell encoded cmd, WMI execution, Script interpreter abuse</td><td>Sysmon, EDR, Windows Events</td></tr>
        <tr><td>Persistence</td><td>New scheduled task, Registry run key, New service installed</td><td>Sysmon, Windows Events</td></tr>
        <tr><td>Privilege Escalation</td><td>Token manipulation, UAC bypass, Sudo abuse</td><td>Sysmon, auditd, Windows Events</td></tr>
        <tr><td>Defense Evasion</td><td>AV disabled, Log cleared, Timestomping, Process hollowing</td><td>Sysmon, EDR, Security Events</td></tr>
        <tr><td>Credential Access</td><td>LSASS dump, Kerberoasting, DCSync, Brute force</td><td>Windows Events, EDR</td></tr>
        <tr><td>Discovery</td><td>Network scan, AD enumeration, Share discovery</td><td>Sysmon, NetFlow, AD logs</td></tr>
        <tr><td>Lateral Movement</td><td>PsExec, WMI remote, RDP brute force, Pass-the-Hash</td><td>Windows Events, NetFlow</td></tr>
        <tr><td>Exfiltration</td><td>DNS tunneling, Large upload, Cloud sync abuse</td><td>DNS, Proxy, DLP, NetFlow</td></tr>
        <tr><td>C2</td><td>Beaconing pattern, DGA domains, Known C2 IPs</td><td>DNS, Proxy, NetFlow, Firewall</td></tr>
        <tr><td>Impact</td><td>Mass file encryption, Volume shadow deletion, Wiper activity</td><td>EDR, Sysmon, File Integrity</td></tr>
    </table>
</div>

<div class="pg-callout pg-callout-info">Open the <strong>SOC Knowledge Base</strong> from the sidebar for full rule details with queries, playbooks, policies, and payloads for each use case.</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="renderKnowledgeBase()">OPEN KNOWLEDGE BASE</button>
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

richPageContent.rulegen = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">SIEM RULE GENERATOR</h1>
    <span class="card-tag" style="position:static">TOOL</span>
</div>

<div class="pg-section">
    <div class="pg-section-title">USAGE</div>
    ${pgCode(`# Generate rules from IOC feed output
python tools/siem-rule-generator.py --input output/iocs.json --platforms all

# Generate for specific platforms
python tools/siem-rule-generator.py --input output/iocs.json --platforms splunk,sentinel,qradar

# Generate from single IOC
python tools/siem-rule-generator.py --ioc "185.220.101.1" --type ip --platforms all

# Generate from CSV
python tools/siem-rule-generator.py --input iocs.csv --format csv --platforms wazuh,elastic`, 'bash')}
</div>

<div class="pg-section">
    <div class="pg-section-title">SUPPORTED OUTPUT FORMATS</div>
    <table class="pg-table">
        <tr><th>Platform</th><th>Format</th><th>Output</th></tr>
        <tr><td>Splunk</td><td>SPL</td><td>Correlation search .conf</td></tr>
        <tr><td>Microsoft Sentinel</td><td>KQL</td><td>Analytics rule JSON</td></tr>
        <tr><td>IBM QRadar</td><td>AQL</td><td>Reference set + rule XML</td></tr>
        <tr><td>Elastic SIEM</td><td>EQL/KQL</td><td>Detection rule TOML</td></tr>
        <tr><td>Wazuh</td><td>XML</td><td>Custom rule + CDB list</td></tr>
        <tr><td>Google Chronicle</td><td>YARA-L</td><td>Detection rule</td></tr>
        <tr><td>Sigma</td><td>YAML</td><td>Generic Sigma rule</td></tr>
    </table>
</div>

<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px">
    <button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button>
</div>
`;

// Remaining SOAR platforms - shorter but present
richPageContent.qradarsoar = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">IBM QRADAR SOAR (RESILIENT)</h1>
    <span class="card-tag" style="position:static">SOAR</span>
</div>
<div class="pg-section">
    <div class="pg-section-title">KEY FEATURES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Dynamic Playbooks</h4><p>Playbooks that adapt based on incident type and artifacts. Condition-based branching for different response paths.</p></div>
        <div class="pg-info-card"><h4>Privacy Module</h4><p>Built-in GDPR, CCPA, and HIPAA breach reporting workflows. Auto-calculate notification deadlines.</p></div>
        <div class="pg-info-card"><h4>MITRE ATT&CK</h4><p>Native ATT&CK technique mapping for incidents. Auto-suggest response actions based on technique.</p></div>
        <div class="pg-info-card"><h4>Artifact Management</h4><p>Structured artifact tracking with auto-enrichment. Link artifacts across related incidents.</p></div>
    </div>
</div>
<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px"><button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button></div>
`;

richPageContent.shuffle = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">SHUFFLE SOAR</h1>
    <span class="card-tag" style="position:static">SOAR</span>
</div>
<div class="pg-section">
    <div class="pg-section-title">KEY FEATURES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Open Source</h4><p>Free, self-hosted SOAR. No licensing costs. Docker-based deployment. Active community.</p></div>
        <div class="pg-info-card"><h4>Wazuh Native</h4><p>Built-in Wazuh integration — trigger workflows from Wazuh alerts automatically.</p></div>
        <div class="pg-info-card"><h4>OpenAPI Apps</h4><p>Any API with OpenAPI/Swagger spec becomes an app. Import specs to auto-create integrations.</p></div>
        <div class="pg-info-card"><h4>Workflow Triggers</h4><p>Webhook triggers, scheduled execution, subflow triggers, and manual execution.</p></div>
    </div>
</div>
<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px"><button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button></div>
`;

richPageContent.thehive = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">THEHIVE + CORTEX</h1>
    <span class="card-tag" style="position:static">SOAR</span>
</div>
<div class="pg-section">
    <div class="pg-section-title">KEY FEATURES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Case Management</h4><p>Full incident case management with tasks, observables, and TTPs. Multi-analyst collaboration.</p></div>
        <div class="pg-info-card"><h4>Cortex Analyzers</h4><p>100+ analyzers for IOC enrichment — VirusTotal, Shodan, AbuseIPDB, MISP, PassiveTotal, etc.</p></div>
        <div class="pg-info-card"><h4>Cortex Responders</h4><p>Automated response actions — block IP, disable user, send email, create ticket.</p></div>
        <div class="pg-info-card"><h4>MISP Integration</h4><p>Bi-directional integration with MISP threat sharing platform. Auto-import/export IOCs.</p></div>
    </div>
</div>
<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px"><button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button></div>
`;

richPageContent.fortisoar = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">FORTISOAR</h1>
    <span class="card-tag" style="position:static">SOAR</span>
</div>
<div class="pg-section">
    <div class="pg-section-title">KEY FEATURES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>Visual Designer</h4><p>Drag-and-drop playbook designer with conditional branching, loops, and parallel execution.</p></div>
        <div class="pg-info-card"><h4>Fortinet Integration</h4><p>Native FortiGate, FortiAnalyzer, FortiSIEM integration. Auto-block threats across Fortinet fabric.</p></div>
        <div class="pg-info-card"><h4>Multi-Tenant</h4><p>MSSP-ready with tenant isolation, custom branding, and per-tenant playbooks.</p></div>
        <div class="pg-info-card"><h4>Recommendation Engine</h4><p>AI-assisted recommendations for response actions based on incident type and historical data.</p></div>
    </div>
</div>
<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px"><button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button></div>
`;

// Remaining SIEM platforms
richPageContent.chronicle = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">GOOGLE CHRONICLE (SecOps)</h1>
    <span class="card-tag" style="position:static">SIEM</span>
</div>
<div class="pg-section">
    <div class="pg-section-title">YARA-L 2.0 EXAMPLES</div>
    ${pgCode(`rule suspicious_powershell_execution {
  meta:
    author = "BlueShell SOC"
    description = "Detects encoded PowerShell execution"
    severity = "HIGH"
    mitre_attack = "T1059.001"

  events:
    $process.metadata.event_type = "PROCESS_LAUNCH"
    $process.principal.process.file.full_path = /.*powershell\\.exe$/ nocase
    $process.principal.process.command_line = /.*(-enc|-EncodedCommand|-ec).*/ nocase

  condition:
    $process
}`, 'yara-l')}
    ${pgCode(`rule brute_force_login {
  meta:
    author = "BlueShell SOC"
    description = "Multiple failed logins followed by success from same IP"
    severity = "HIGH"
    mitre_attack = "T1110"

  events:
    $fail.metadata.event_type = "USER_LOGIN"
    $fail.metadata.vendor_name = "Microsoft"
    $fail.security_result.action = "BLOCK"
    $fail.principal.ip = $ip

    $success.metadata.event_type = "USER_LOGIN"
    $success.security_result.action = "ALLOW"
    $success.principal.ip = $ip

    $fail.metadata.event_timestamp.seconds < $success.metadata.event_timestamp.seconds

  match:
    $ip over 15m

  condition:
    #fail > 10 and $success
}`, 'yara-l')}
</div>
<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px"><button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button></div>
`;

richPageContent.visionone = `
${pgBack()}
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <h1 style="margin:0;border:none;padding:0">TREND MICRO VISION ONE</h1>
    <span class="card-tag" style="position:static">XDR</span>
</div>
<div class="pg-section">
    <div class="pg-section-title">SEARCH QUERY EXAMPLES</div>
    ${pgCode(`-- Suspicious PowerShell execution
eventId:1 AND processFilePath:"*powershell.exe" AND processCmd:"*encodedcommand*"

-- Ransomware indicators
eventId:11 AND (objectFilePath:"*.encrypted" OR objectFilePath:"*.locked" OR objectFilePath:"*.crypto")

-- Lateral movement via PsExec
eventId:1 AND processFilePath:"*psexec*" AND objectFilePath:"*PSEXESVC*"`, 'text')}
</div>
<div class="pg-section">
    <div class="pg-section-title">KEY CAPABILITIES</div>
    <div class="pg-grid">
        <div class="pg-info-card"><h4>XDR Correlation</h4><p>Cross-layer detection across email, endpoint, server, cloud workload, and network.</p></div>
        <div class="pg-info-card"><h4>Workbench</h4><p>Centralized investigation workspace with timeline view and automated evidence collection.</p></div>
        <div class="pg-info-card"><h4>Detection Models</h4><p>Custom YAML-based detection models with multi-condition matching and severity scoring.</p></div>
        <div class="pg-info-card"><h4>Response Actions</h4><p>Isolate endpoints, block files, quarantine email, terminate processes — all from one console.</p></div>
    </div>
</div>
<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:20px"><button class="btn-hack" onclick="goHome()">◂ DASHBOARD</button></div>
`;
